# This is the development file
version: "3.7"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: "unless-stopped"
    environment:
      NODE_ENV: development
      ENV_MESSAGE: ${BACKEND_MESSAGE}

  frontend:
    build: ./frontend
    ports:
      # Run dev server on host port 8080
      - "80:80"
    restart: "unless-stopped"

